<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Database Table Prefix
    |--------------------------------------------------------------------------
    |
    | Default database table prefix used when scaffolding Eloquent models.
    | Set to '' if you prefer standard Laravel table names (e.g. 'order_payments').
    | Set to 'tbl_' if your database uses a custom table prefix.
    |
    */
    'table_prefix' => '',

    /*
    |--------------------------------------------------------------------------
    | Database Table Naming Convention
    |--------------------------------------------------------------------------
    |
    | Strategy for scaffolding model table names from module name.
    | Options: 'snake_plural' (order_payments), 'snake_singular' (order_payment)
    |
    */
    'table_naming' => 'snake_plural',

    /*
    |--------------------------------------------------------------------------
    | Controller Action Naming Style
    |--------------------------------------------------------------------------
    |
    | Defines controller action method names generated by make:mod.
    | Options:
    |   - 'restful' (index, show, store, update, destroy)
    |   - 'handler' (HandlerGetAll, HandlerGetById, HandlerDeleteById)
    |
    */
    'controller_style' => 'restful',

    /*
    |--------------------------------------------------------------------------
    | Automatic Registration Options
    |--------------------------------------------------------------------------
    |
    | Automatically register generated module service providers in bootstrap/providers.php
    | and append RESTful routes to routes/api.php upon module creation.
    |
    */
    'auto_register_provider' => true,
    'auto_register_route' => true,
];
